---
management:
  health:
    ldap:
      enabled: false

ebics:
  api:
    clients:
      testclient-admin-xy:
        key: abc1234
        role: admin
      testclient-api-xy:
        key: abc1234
      testclient-api-backup:
        key: abc1234
        role: backup

spring:
  security:
    user:
      name: nobody
      password: pass